server {
    listen 8080;
    server_name localhost;

    root /var/www/html/public;
    index index.php index.html;

    charset utf-8;
    client_max_body_size 200M;
    access_log off;
    error_log /var/www/html/storage/logs/nginx/error.log warn;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass baseplate-php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;

        fastcgi_connect_timeout 120;
        fastcgi_send_timeout    120;
        fastcgi_read_timeout    120;

        fastcgi_intercept_errors on;
    }

    # 504 에러가 발생하면 각각 아래 URL 주소로 내부 리다이렉트
    error_page 504 /busy.html;

    # max-children 초과 시 보여줄 busy.html 위치 설정
    location = /busy.html {
        root /var/www/html/resources/views/errors;
        internal;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
